### ISSUE TITLE
Broken on Chrome

### ISSUE THREAD

**Issue by colinschoen** [mobz/get-timezone-offset#1]
There appears to be a regression with Chrome. It is calculating incorrect timezone offsets in Chrome. You can reproduce some failures by running the provided test suite on Chrome.

Chrome version: `81.0.4044.113 (Official Build) (64-bit)`

```TAP version 13
test.browser.js:7615 # getTimezoneOffset
test.browser.js:7615 ok 1 UTC at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 2 Pacific/Midway at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 3 Pacific/Honolulu at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 4 America/Anchorage at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 5 America/Los_Angeles at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 6 America/Denver at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 7 America/Mexico_City at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 8 America/New_York at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 9 America/Curacao at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 10 America/Argentina/Buenos_Aires at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 11 America/Noronha at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 12 Atlantic/Azores at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 13 Africa/Casablanca at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 14 Africa/Lagos at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 15 Africa/Johannesburg at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 16 Europe/Moscow at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 17 Asia/Dubai at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 18 Asia/Ashgabat at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 19 Asia/Dhaka at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 20 Asia/Bangkok at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 21 Asia/Harbin at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 22 Asia/Seoul at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 23 Australia/Brisbane at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 24 Pacific/Norfolk at 2017-01-01T12:00:00.000Z
test.browser.js:7615 not ok 25 Pacific/Funafuti at 2017-01-01T12:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: |-
test.browser.js:7615       -720
test.browser.js:7615     actual: |-
test.browser.js:7615       -2160
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Pacific/Funafuti at 2017-01-01T12:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 ok 26 Australia/Melbourne at 2016-01-15T12:00:00.000Z
test.browser.js:7615 ok 27 Australia/Melbourne at 2016-02-15T12:00:00.000Z
test.browser.js:7615 ok 28 Australia/Melbourne at 2016-03-15T12:00:00.000Z
test.browser.js:7615 ok 29 Australia/Melbourne at 2016-04-15T13:00:00.000Z
test.browser.js:7615 ok 30 Australia/Melbourne at 2016-05-15T13:00:00.000Z
test.browser.js:7615 ok 31 Australia/Melbourne at 2016-06-15T13:00:00.000Z
test.browser.js:7615 ok 32 Australia/Melbourne at 2016-07-15T13:00:00.000Z
test.browser.js:7615 ok 33 Australia/Melbourne at 2016-08-15T13:00:00.000Z
test.browser.js:7615 ok 34 Australia/Melbourne at 2016-09-15T13:00:00.000Z
test.browser.js:7615 ok 35 Australia/Melbourne at 2016-10-15T12:00:00.000Z
test.browser.js:7615 ok 36 Australia/Melbourne at 2016-11-15T12:00:00.000Z
test.browser.js:7615 ok 37 Australia/Melbourne at 2016-12-15T12:00:00.000Z
test.browser.js:7615 ok 38 Australia/Eucla at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 39 Antarctica/Davis at 1923-05-03T13:10:00.000Z
test.browser.js:7615 ok 40 Antarctica/Davis at 2017-01-01T12:00:00.000Z
test.browser.js:7615 ok 41 Asia/Tehran at 1923-05-03T13:10:00.000Z
test.browser.js:7615 not ok 42 Asia/Tehran at 1970-01-01T00:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: |-
test.browser.js:7615       -210
test.browser.js:7615     actual: |-
test.browser.js:7615       1230
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Asia/Tehran at 1970-01-01T00:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 not ok 43 Asia/Tehran at 2000-01-01T00:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: |-
test.browser.js:7615       -210
test.browser.js:7615     actual: |-
test.browser.js:7615       1230
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Asia/Tehran at 2000-01-01T00:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 ok 44 Asia/Tehran at 2026-06-06T06:06:06.000Z
test.browser.js:7615 ok 45 Pacific/Apia at 1923-05-03T13:10:00.000Z
test.browser.js:7615 not ok 46 Pacific/Apia at 2000-01-01T00:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: 660
test.browser.js:7615     actual:   2100
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Pacific/Apia at 2000-01-01T00:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 ok 47 Pacific/Apia at 2016-03-01T12:00:00.000Z
test.browser.js:7615 ok 48 Pacific/Apia at 2026-06-06T06:06:06.000Z
test.browser.js:7615 ok 49 Pacific/Chatham at 1923-05-03T13:10:00.000Z
test.browser.js:7615 not ok 50 Pacific/Chatham at 1970-01-01T00:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: |-
test.browser.js:7615       -765
test.browser.js:7615     actual: |-
test.browser.js:7615       675
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Pacific/Chatham at 1970-01-01T00:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 ok 51 Pacific/Chatham at 2016-03-01T12:00:00.000Z
test.browser.js:7615 ok 52 Pacific/Chatham at 2026-06-06T06:06:06.000Z
test.browser.js:7615 not ok 53 Africa/Monrovia at 1900-01-01T00:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: 44
test.browser.js:7615     actual:   1484
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Africa/Monrovia at 1900-01-01T00:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 not ok 54 Africa/Monrovia at 1968-01-01T00:00:00.000Z
test.browser.js:7615   ---
test.browser.js:7615     operator: equal
test.browser.js:7615     expected: 45
test.browser.js:7615     actual:   1485
test.browser.js:7615     stack: |-
test.browser.js:7615       Error: Africa/Monrovia at 1968-01-01T00:00:00.000Z
test.browser.js:7615           at Test.assert [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8068:54)
test.browser.js:7615           at Test.bound [as _assert] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.equal (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8229:10)
test.browser.js:7615           at Test.bound [as equal] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8776:5
test.browser.js:7615           at Array.forEach (<anonymous>)
test.browser.js:7615           at Test.<anonymous> (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:8772:9)
test.browser.js:7615           at Test.bound [as _cb] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615           at Test.run (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7936:10)
test.browser.js:7615           at Test.bound [as run] (file:///Users/colinschoen/Projects/get-timezone-offset/test.browser.js:7920:32)
test.browser.js:7615   ...
test.browser.js:7615 ok 55 Africa/Monrovia at 2017-01-01T12:00:00.000Z
test.browser.js:7615 
test.browser.js:7615 1..55
test.browser.js:7615 # tests 55
test.browser.js:7615 # pass  48
test.browser.js:7615 # fail  7
test.browser.js:7615 
```

**Comment by mobz** [comment]
This looks like a bug in chrome. A minimum repro case is 
`(new Intl.DateTimeFormat('en-US', {timeZone: 'Pacific/Funafuti', hour12: false, year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric'})).format(new Date(1483272000000));`
which should return `1/2/2017, 00:00` and does in node, and safari.
But chrome returns `1/2/2017, 24:00` which is wrong by a whole 24 hours. :(
Interestingly there IS a leap second at 31/12/2016 24:00 (one day before the test day - maybe chrome is getting confused somehow) ?
Not sure exactly how to work around this bug, since 24:00 is a valid time in the case of a leap second... I'll look into this further

**Comment by mobz** [comment]
Tracking bug https://bugs.chromium.org/p/chromium/issues/detail?id=1077117

**Comment by mobz** [comment]
Also being discussed here https://github.com/tc39/ecma402/issues/402

**Comment by mobz** [comment]
Not a bug in chrome, so much as a bug in the ecmascript spec which chrome started following and other browsers do not (yet)

**Comment by colinschoen** [comment]
Thanks for looking into it.

**Comment by colinschoen** [comment]
@mobz would you mind publishing the new version (`1.0.4`)

**Comment by mobz** [comment]
Done

**Comment by colinschoen** [comment]
Thanks again
